language: python

python:
  - 2.7
  
install:
  - pip install -r requirements.txt
  - python manage.py migrate
  
script:
  - python manage.py behave
  
notifications:
  email:
    on_success: never
    on_failure: never
    on_error: never
